Sprint 1
sergromm/middle.messenger.praktikum.yandex pull request #1
Opened 2022-02-17 14:52 UTC by sergromm

2022-02-17 16:42 UTC, DmitryKhitrin requested changes
Приложите пожалуйста ссылку на netlify в readme

2022-02-17 18:01 UTC, sergromm commented on src/components/chatFeed.tmpl.js
> +  <ul class="messages">
Это критично на этом спринте или можно на следующем добавить? Я генерацию отложил, не думал что сейчас пригодится.

2022-02-18 09:14 UTC, DmitryKhitrin commented on src/components/chatFeed.tmpl.js
> +  <ul class="messages">
Можно в следующем, но там это будет критично

2022-02-18 09:14 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки и удачи в следующем спринте!)

2022-02-18 10:21 UTC, merged